#pragma once

#define REINFORCEMENT_LEARNING 0
#define SPARSE_CODING 1
#define PIANO_ROLL_PREDICTION 2
#define SPRITE_ANIMATION_PREDICTION 3

// Choose program
#define SUBPROGRAM_EXECUTE SPRITE_ANIMATION_PREDICTION